ALTER PROC FI_SP_ConsBeneficiario
	@IdCliente BIGINT = NULL,
	@Id BIGINT = NULL
AS
BEGIN
	IF(ISNULL(@IdCliente,0) = 0 AND ISNULL(@Id,0) = 0)
	SELECT ID, CPF, NOME FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE IF (ISNULL(@IdCliente,0) <> 0)
		SELECT ID, CPF, NOME FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IdCliente
	ELSE IF (ISNULL(@Id,0) <> 0)
		SELECT ID, CPF, NOME FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @Id
END