ALTER PROC FI_SP_IncBeneficiario
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (14),
	@IdCliente	   BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IdCliente)

	SELECT SCOPE_IDENTITY()
END